name: GeoJSON Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        playwright install --with-deps

    - name: Run tests with Allure results
      run: |
        pytest Tests/ --alluredir=allure-results --headed=false

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

  allure-report:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Download Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure report
      run: |
        pip install allure-pytest
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        ./allure-2.27.0/bin/allure generate allure-results -o allure-report --clean

    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
